// Code generated by mfd-generator v0.4.5; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

var Columns = struct {
	GigachatMessage struct {
		ID, Message string
	}
}{
	GigachatMessage: struct {
		ID, Message string
	}{
		ID:      "messageid",
		Message: "message",
	},
}

var Tables = struct {
	GigachatMessage struct {
		Name, Alias string
	}
}{
	GigachatMessage: struct {
		Name, Alias string
	}{
		Name:  "salesbot.gigachatmessages",
		Alias: "t",
	},
}

type GigachatMessage struct {
	tableName struct{} `pg:"salesbot.gigachatmessages,alias:t,discard_unknown_columns"`

	ID      int    `pg:"messageid,pk"`
	Message string `pg:"message,use_zero"`
}
