// Code generated by mfd-generator v0.4.5; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

const condition = "?.? = ?"

// base filters
type applier func(query *orm.Query) (*orm.Query, error)

type search struct {
	appliers []applier
}

func (s *search) apply(query *orm.Query) {
	for _, applier := range s.appliers {
		query.Apply(applier)
	}
}

func (s *search) where(query *orm.Query, table, field string, value interface{}) {
	query.Where(condition, pg.Ident(table), pg.Ident(field), value)
}

func (s *search) WithApply(a applier) {
	if s.appliers == nil {
		s.appliers = []applier{}
	}
	s.appliers = append(s.appliers, a)
}

func (s *search) With(condition string, params ...interface{}) {
	s.WithApply(func(query *orm.Query) (*orm.Query, error) {
		return query.Where(condition, params...), nil
	})
}

// Searcher is interface for every generated filter
type Searcher interface {
	Apply(query *orm.Query) *orm.Query
	Q() applier

	With(condition string, params ...interface{})
	WithApply(a applier)
}

type GigachatMessageSearch struct {
	search

	ID           *int
	Message      *string
	Tgid         *int
	IDs          []int
	MessageILike *string
}

func (gms *GigachatMessageSearch) Apply(query *orm.Query) *orm.Query {
	if gms == nil {
		return query
	}
	if gms.ID != nil {
		gms.where(query, Tables.GigachatMessage.Alias, Columns.GigachatMessage.ID, gms.ID)
	}
	if gms.Message != nil {
		gms.where(query, Tables.GigachatMessage.Alias, Columns.GigachatMessage.Message, gms.Message)
	}
	if gms.Tgid != nil {
		gms.where(query, Tables.GigachatMessage.Alias, Columns.GigachatMessage.Tgid, gms.Tgid)
	}
	if len(gms.IDs) > 0 {
		Filter{Columns.GigachatMessage.ID, gms.IDs, SearchTypeArray, false}.Apply(query)
	}
	if gms.MessageILike != nil {
		Filter{Columns.GigachatMessage.Message, *gms.MessageILike, SearchTypeILike, false}.Apply(query)
	}

	gms.apply(query)

	return query
}

func (gms *GigachatMessageSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if gms == nil {
			return query, nil
		}
		return gms.Apply(query), nil
	}
}
